name: GitHub actions

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  repository_dispatch:
    types: ["**"]

env:
  BUILD_TYPE: Release
  WIN_LIBOQS_INSTALL_PATH: C:\liboqs
  WIN_PKG_CONFIG_PATH: C:\Strawberry\c\lib\pkgconfig

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install liboqs Windows
        shell: cmd
        run: |
          git clone --branch main --single-branch --depth 1 https://github.com/jplomas/liboqs
          cmake -S liboqs -B liboqs\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.WIN_LIBOQS_INSTALL_PATH}} -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON
          cmake --build liboqs\build --parallel 4
          cmake --build liboqs\build --target install

      - name: Configure pkgconfig Windows
        shell: cmd
        run: |
          copy .\.config\liboqs-go.pc.win64 ${{env.WIN_PKG_CONFIG_PATH}}\liboqs-go.pc

      - name: Run unit tests Windows
        shell: cmd
        run: |
          set PATH=%PATH%;${{env.WIN_LIBOQS_INSTALL_PATH}}\bin
          go test -v -run "TestSignatureCorrectness|TestSignatureCorrectnessWithCtxStr" .\oqstests
